# Generated by Django 4.1.3 on 2022-11-12 21:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ict_contracts', '0001_initial'),
        ('ict_vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='Total Project Value')),
                ('amount_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='Amount Outstanding')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('On track', 'On track'), ('Delayed', 'Delayed'), ('Stopped', 'Stopped'), ('Completed', 'Completed')], default='Not Started', max_length=150)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='ict_contracts.contract')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='ict_vendors.vendor', verbose_name='Service Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.CharField(choices=[('Project Manager', 'Project Manager'), ('Technical Lead', 'Technical Lead'), ('Technical Support', 'Technical Support'), ('User Support', 'User Suport'), ('Business User', 'Business User')], default='Project Manager', max_length=150, verbose_name='Project Role')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profiles', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_members', to='ict_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('planned_end_date', models.DateField(verbose_name='Planned End Date')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Actual End Date')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress - On Track', 'In Progress - On Track'), ('In Progress - Delayed', 'In Progress - Delayed'), ('Stopped', 'Stopped'), ('Completed', 'Completed')], default='Not Started', max_length=200)),
                ('weight', models.PositiveIntegerField(verbose_name='Weight in %')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='Milestone Amount')),
                ('is_paid', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='ict_projects.project')),
            ],
        ),
    ]
