# Generated by Django 4.1.3 on 2022-11-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='amount_outstanding',
        ),
    ]
