# Generated by Django 4.1.3 on 2022-11-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ict_contracts', '0001_initial'),
        ('ict_accounts', '0003_alter_profile_photo'),
        ('ict_projects', '0002_remove_project_amount_outstanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts', to='ict_contracts.contract'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team', to='ict_accounts.profile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team', to='ict_projects.project'),
        ),
    ]
