# Generated by Django 4.1.3 on 2022-11-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ict_accounts', '0003_alter_profile_photo'),
        ('ict_projects', '0003_alter_project_contract_alter_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ict_accounts.profile'),
        ),
    ]
