# Generated by Django 4.1.3 on 2022-11-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_projects', '0004_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
