# Generated by Django 4.1.3 on 2022-11-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_projects', '0005_alter_milestone_description_alter_milestone_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
