# Generated by Django 4.1.3 on 2022-11-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_projects', '0006_alter_team_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
    ]
