# Generated by Django 4.1.3 on 2022-12-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_projects', '0007_remove_project_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('On Track', 'On Track'), ('Delayed', 'Delayed'), ('Stopped', 'Stopped'), ('Completed', 'Completed')], default='Not Started', max_length=200),
        ),
    ]
