# Generated by Django 4.1.3 on 2022-12-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_projects', '0008_alter_milestone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('On Track', 'On Track'), ('Delayed', 'Delayed'), ('Stopped', 'Stopped'), ('Completed', 'Completed')], default='Not Started', max_length=150),
        ),
    ]
