# Generated by Django 4.1.3 on 2022-12-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_projects', '0009_alter_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-id',)},
        ),
    ]
