# Generated by Django 4.1.3 on 2022-12-02 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_projects', '0011_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-id',)},
        ),
    ]
