# Generated by Django 4.1.3 on 2022-12-03 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ict_contracts', '0001_initial'),
        ('ict_projects', '0012_alter_milestone_options_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='ict_contracts.contract'),
        ),
    ]
