# Generated by Django 4.1.3 on 2023-01-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_projects', '0013_alter_project_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(None, 'Select Status'), ('Not Started', 'Not Started'), ('On Track', 'On Track'), ('Delayed', 'Delayed'), ('Stopped', 'Stopped'), ('Completed', 'Completed')], default='Not Started', max_length=150),
        ),
    ]
