# Generated by Django 4.1.3 on 2022-11-12 21:25

from django.db import migrations, models
import ict_accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/images/default2.png', upload_to=ict_accounts.models.user_directory_path),
        ),
    ]
