# Generated by Django 4.1.3 on 2022-11-17 21:54

from django.db import migrations, models
import ict_accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_accounts', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default2.png', upload_to=ict_accounts.models.user_directory_path),
        ),
    ]
