# Generated by Django 4.1.3 on 2023-01-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_accounts', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
