# Generated by Django 4.1.3 on 2023-01-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_accounts', '0004_alter_account_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id']},
        ),
    ]
