# Generated by Django 4.1.3 on 2023-01-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_accounts', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
