# Generated by Django 4.1.3 on 2022-12-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_contracts', '0005_alter_contract_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(default='Ok', max_length=300),
        ),
    ]
