# Generated by Django 4.1.3 on 2022-12-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_contracts', '0006_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
    ]
