# Generated by Django 4.1.3 on 2022-11-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('location_footprint', models.CharField(choices=[(None, 'Select company nationality'), ('LOCAL', 'Local'), ('MNC', 'Multinational Company'), ('FOREIGN', 'Foreign Based')], max_length=200, verbose_name='Company Footprint')),
                ('supplier_channel', models.CharField(blank=True, choices=[(None, 'Select supllier channel'), ('Direct-OEM', 'Direct-OEM'), ('INDIRECT-OEM', 'Indirect-OEM'), ('LSP', 'Licensed Solutions Provider'), ('LCR', 'Local Certified Reseller'), ('LSS', 'Local Sole Supplier ')], max_length=200, null=True, verbose_name='Supplier Channel')),
                ('contact_person', models.CharField(default=None, max_length=200, verbose_name='Account Manager')),
                ('contact_phone', models.CharField(max_length=15, verbose_name='Account Manager Phone')),
                ('email', models.EmailField(max_length=100)),
                ('physical_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Physical Address')),
                ('postal_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Postal Address')),
                ('executive_contact', models.CharField(blank=True, max_length=200, null=True, verbose_name='Executive Contact Person')),
                ('exe_contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Executive Contact Phone')),
                ('logo', models.ImageField(blank=True, default='logo.png', null=True, upload_to='company_logos/%Y')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
