# Generated by Django 4.1.3 on 2023-03-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_vendors', '0002_alter_vendor_location_footprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='company_logos/%Y'),
        ),
    ]
