# Generated by Django 4.1.3 on 2022-11-12 21:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ict_contracts', '0001_initial'),
        ('ict_vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('software_category', models.CharField(choices=[(None, 'Select software category'), ('Productivity', 'Productivity'), ('Enterprise Resource Planning', 'Enterprise Resource Planning'), ('Learning Management System', 'Learning Management System'), ('Operating System', 'Operating System'), ('Database Management System', 'Database Management System'), ('Business Intelligence', 'Business Intelligence'), ('Data & Statistical Analytics', 'Data & Statistical Analytics'), ('Network Management', 'Network Management'), ('IT Service Management', 'IT Service Management'), ('Communication', 'Communication'), ('Collaboration', 'Collaboration'), ('Business Application', 'Business Application'), ('Academic Specialist Software', 'Academic Specialist Software')], max_length=250, verbose_name='Software Category')),
                ('renewal_term', models.CharField(choices=[(None, 'Select renewal terms'), ('Annual Renewal', 'Annual Renewal'), ('Once-Off', 'Once-Off'), ('Contract Term Linked', 'Contract Term Linked'), ('Pepertual', 'Pepertual')], max_length=250, verbose_name='Renewal Term')),
                ('pricing_model', models.CharField(choices=[(None, 'Select pricing model'), ('Support Retainer', 'Support Retainer'), ('Seats', 'Seats'), ('Cores', 'Cores'), ('Minutes', 'Minutes'), ('Storage', 'Storage'), ('Minutes & Storage', 'Minutes & Storage')], max_length=200, verbose_name='Pricing Model')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Inception Date')),
                ('next_renewal_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Next Renewal Date')),
                ('current_cost', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='Current Cost')),
                ('renewal_status', models.CharField(choices=[('Not Started', 'Not Started'), ('Supplier Invitation', 'Supplier Invitation'), ('Purchase Request', 'Purchase Request'), ('Purchase Order', 'Purchase Order'), ('Invoice', 'Invoice'), ('Paid', 'Paid')], default='Not Started', max_length=250, verbose_name='Renewal Status')),
                ('user_base', models.CharField(choices=[(None, 'Select user base'), ('Students', 'Students'), ('Academics', 'Academics'), ('Academics & Students', 'Academics & Students'), ('Admin Staff', 'Admin Staff'), ('Admin Staff & Students', 'Admin Staff & Students'), ('All Staff', 'All Staff'), ('All Staff & Students', 'All Staff & Students'), ('Academics Specialist', 'Academics Specialist'), ('ICT Staff', 'ICT Staff')], max_length=250, verbose_name='User Base')),
                ('num_admin_users', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Admin Users')),
                ('num_end_users', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of End Users')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract', to='ict_contracts.contract')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='licenses', to=settings.AUTH_USER_MODEL)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='ict_vendors.vendor', verbose_name='Service Provider')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
