# Generated by Django 4.1.3 on 2022-12-05 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ict_contracts', '0001_initial'),
        ('ict_vendors', '0001_initial'),
        ('ict_licenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='renewal_status',
        ),
        migrations.AddField(
            model_name='license',
            name='renewal',
            field=models.BooleanField(default=False, verbose_name='Renew License'),
        ),
        migrations.AlterField(
            model_name='license',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='licenses', to='ict_contracts.contract'),
        ),
        migrations.AlterField(
            model_name='license',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='ict_vendors.vendor', verbose_name='Service Provider'),
        ),
    ]
