# Generated by Django 4.1.3 on 2022-12-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_licenses', '0002_remove_license_renewal_status_license_renewal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='renewal_term',
            field=models.CharField(choices=[(None, 'Select renewal terms'), ('Annual Renewal', 'Annual Renewal'), ('Once-Off', 'Once-Off'), ('Term Contract', 'Term Contract'), ('Pepertual', 'Pepertual')], max_length=250, verbose_name='Renewal Term'),
        ),
    ]
