# Generated by Django 4.1.3 on 2023-01-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ict_accounts', '0003_alter_profile_photo'),
        ('ict_licenses', '0003_alter_license_renewal_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='licenses', to='ict_accounts.profile'),
        ),
        migrations.AlterField(
            model_name='license',
            name='software_category',
            field=models.CharField(choices=[(None, 'Select software category'), ('Productivity', 'Productivity'), ('Collaboration', 'Collaboration'), ('Enterprise Resource Planning', 'Enterprise Resource Planning'), ('Learning Management System', 'Learning Management System'), ('Operating System', 'Operating System'), ('Database Management System', 'Database Management System'), ('Business Intelligence', 'Business Intelligence'), ('Data & Statistical Analytics', 'Data & Statistical Analytics'), ('Network Management', 'Network Management'), ('IT Service Management', 'IT Service Management'), ('Communication', 'Communication'), ('Collaboration', 'Collaboration'), ('Business Application', 'Business Application'), ('Academic Specialist Software', 'Academic Specialist Software')], max_length=250, verbose_name='Software Category'),
        ),
    ]
