# Generated by Django 4.1.3 on 2023-01-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_licenses', '0004_alter_license_owner_alter_license_software_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='software_category',
            field=models.CharField(choices=[('Productivity', 'Productivity'), ('Collaboration', 'Collaboration'), ('Enterprise Resource Planning', 'Enterprise Resource Planning'), ('Learning Management System', 'Learning Management System'), ('Operating System', 'Operating System'), ('Database Management System', 'Database Management System'), ('Business Intelligence', 'Business Intelligence'), ('Data & Statistical Analytics', 'Data & Statistical Analytics'), ('Network Management', 'Network Management'), ('IT Service Management', 'IT Service Management'), ('Communication', 'Communication'), ('Collaboration', 'Collaboration'), ('Business Application', 'Business Application'), ('Academic Specialist Software', 'Academic Specialist Software')], max_length=250, verbose_name='Software Category'),
        ),
    ]
