# Generated by Django 4.1.3 on 2023-01-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_licenses', '0007_alter_license_software_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='next_renewal_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Next Renewal Date'),
        ),
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inception Date'),
        ),
    ]
