# Generated by Django 4.1.3 on 2023-01-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_licenses', '0008_alter_license_next_renewal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='next_renewal_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Next Renewal Date'),
        ),
    ]
