# Generated by Django 4.1.3 on 2023-01-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_licenses', '0010_rename_renewal_license_is_renewed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewal',
            name='renewal_count',
        ),
    ]
