# Generated by Django 4.1.3 on 2023-02-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_licenses', '0011_remove_renewal_renewal_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={},
        ),
    ]
