# Generated by Django 4.1.3 on 2023-03-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_licenses', '0016_alter_license_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ('-id',)},
        ),
    ]
