# Generated by Django 4.1.3 on 2023-03-03 19:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_licenses', '0018_licenserenewal_delete_renewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserenewal',
            name='renewal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
