# Generated by Django 4.1.3 on 2023-03-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_licenses', '0020_alter_licenserenewal_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Inception Date'),
        ),
    ]
