# Generated by Django 4.1.3 on 2023-03-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_licenses', '0021_alter_license_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inception Date'),
        ),
    ]
